# Generated by Django 5.0.3 on 2024-08-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
