# Generated by Django 5.0.3 on 2024-08-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employees_phone_alter_employees_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='hourjob',
            field=models.IntegerField(default=0),
        ),
    ]
