# Generated by Django 5.0.3 on 2024-08-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employees_hourjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='salarypay',
            field=models.IntegerField(default=0),
        ),
    ]
