# Generated by Django 5.0.3 on 2024-08-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employees_salarypay'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='salary_per_hour',
            field=models.IntegerField(default=0),
        ),
    ]
