# Generated by Django 5.0.3 on 2024-08-17 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='note',
            new_name='notes',
        ),
    ]
