# Generated by Django 5.0.3 on 2024-08-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_note_attendance_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='card',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
