# Generated by Django 5.0.3 on 2024-08-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_employees_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='accompte',
            field=models.IntegerField(default=0),
        ),
    ]
