# Generated by Django 5.0.3 on 2024-08-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_employees_accompte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=25)),
                ('monto', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
